/*
 * AttendedRepository.java - Data Access Layer for Attended Entity
 * 
 * PURPOSE:
 * This repository interface provides database access methods for the Attended entity.
 * It manages doctor responses and treatments for patient queries.
 * 
 * INHERITED METHODS (from JpaRepository):
 * - save(Attended) - Insert or update an attended record
 * - findById(Integer) - Find attended record by query ID
 * - findAll() - Get all attended records
 * - delete(Attended) - Delete an attended record
 * And many more CRUD operations...
 * 
 * CUSTOM METHODS:
 * - findByQid(Integer) - Find attended record for a specific query
 *   Returns Optional<Attended> (may be empty if query not yet attended)
 *   Spring auto-generates: SELECT * FROM attended WHERE qid = ?
 * 
 * OPTIONAL RETURN TYPE:
 * Using Optional prevents NullPointerException when a query hasn't been attended yet
 * Service layer can check: if (optional.isPresent()) { ... }
 * 
 * DATABASE INTERACTION:
 * This repository bridges Java objects and MySQL 'attended' table
 * All SQL is auto-generated by Spring Data JPA
 */
package online.ppriyanshu26.docdispatch.repository;

import online.ppriyanshu26.docdispatch.entity.Attended;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.Optional;

@Repository
public interface AttendedRepository extends JpaRepository<Attended, Integer> {
    Optional<Attended> findByQid(Integer qid);
}
