# Server Configuration
server.port=${SERVER_PORT}

# MongoDB Configuration
spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.auto-index-creation=true

# Logging
logging.level.org.springframework.data.mongodb=DEBUG

# CORS Configuration (for Flutter app)
spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
